<a href="https://colab.research.google.com/github/1122naveen/personal-portfolio-/blob/master/Movies_Recommendation_System_using_Machine_Learning_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [2]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [15]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/movies.csv', engine='python', on_bad_lines='skip')

In [14]:
file_path = '/content/movies.csv'
try:
    with open(file_path, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            if i >= 185 and i <= 195: # Check lines around row 190
                print(f"Line {i+1}: {line.strip()}")
except Exception as e:
    print(f"Error reading file: {e}")

Line 186: 286,100000000,Action Drama Mystery Thriller,http://www.warnerbros.com/eraser,9268,suicide ambush showdown hostage traitor,en,Eraser,"U.S. Marshall John Kruger erases the identities of people enrolled in the Witness Protection Program. His current assignment is to protect Lee Cullen, who's uncovered evidence that the weapons manufacturer she works for has been selling to terrorist groups. When Kruger discovers that there's a corrupt agent within the program, he must guard his own life while trying to protect Lee's.",24.507987,"[{""name"": ""Kopelson Entertainment"", ""id"": 824}, {""name"": ""Warner Bros."", ""id"": 6194}]","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso_3166_1"": ""US"", ""name"": ""United States of America""}]",1996-06-21,242295562,115.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,He will erase your past to protect your future.,Eraser,5.6,543,Arnold Schwarzenegger James Caan Vanessa Williams James Coburn Robert Pastorelli,"[{'name': 

In [16]:
# printing the first 5 rows of the dataframe
movies_data.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [17]:
# number of rows and columns  in the data frame
movies_data.shape

(189, 24)

In [18]:
# selecting the relevant features for recommendation
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [19]:
# replacwing the null values with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [21]:
# combining all the 5 selected features
combined_features = movies_data['genres']+''+movies_data['keywords']+''+movies_data['tagline']+''+movies_data['cast']+''+movies_data['director']

In [22]:
print(combined_features)

0      Action Adventure Fantasy Science Fictioncultur...
1      Adventure Fantasy Actionocean drug abuse exoti...
2      Action Adventure Crimespy based on novel secre...
3      Action Crime Drama Thrillerdc comics crime fig...
4      Action Adventure Science Fictionbased on novel...
                             ...                        
184    Action Drama Mystery Thrillersuicide ambush sh...
185    Drama Westernbounty hunter hero plantation soc...
186    Drama Animation Familyparis based on novel jud...
187    Adventure Animation Comedy Family Fantasycentr...
188    Action Adventure Thrillerairplane number in ti...
Length: 189, dtype: object


In [23]:
# coverting the text data to feature vectors
vectorizer = TfidfVectorizer()

In [24]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [25]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4687 stored elements and shape (189, 2410)>
  Coords	Values
  (0, 13)	0.06491549588764721
  (0, 33)	0.06765640594992742
  (0, 739)	0.11681269182724222
  (0, 1871)	0.08548733249889726
  (0, 791)	0.23586962930874425
  (0, 405)	0.21864978331400498
  (0, 870)	0.18266558054100696
  (0, 1976)	0.3269401179706429
  (0, 2298)	0.16751782187574396
  (0, 426)	0.21864978331400498
  (0, 1962)	0.23586962930874425
  (0, 2107)	0.09286271095357318
  (0, 2376)	0.14498237657841176
  (0, 1569)	0.12533504899784653
  (0, 1610)	0.23586962930874425
  (0, 1844)	0.1769945869820644
  (0, 2383)	0.20643210814540433
  (0, 2408)	0.19695534303908388
  (0, 1840)	0.20643210814540433
  (0, 1935)	0.23586962930874425
  (0, 2322)	0.23586962930874425
  (0, 2013)	0.21864978331400498
  (0, 1266)	0.23586962930874425
  (0, 1444)	0.19695534303908388
  (0, 1796)	0.23586962930874425
  :	:
  (187, 1375)	0.22418980977090927
  (187, 575)	0.22418980977090927
  (188, 13)	0.06

Cosine Similarity

In [26]:
# getting the similarity scores using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [27]:
print(similarity)

[[1.         0.08742884 0.00927382 ... 0.         0.00435073 0.03677182]
 [0.08742884 1.         0.0353334  ... 0.         0.0075242  0.00789863]
 [0.00927382 0.0353334  1.         ... 0.05999825 0.00458946 0.00925323]
 ...
 [0.         0.         0.05999825 ... 1.         0.01662204 0.        ]
 [0.00435073 0.0075242  0.00458946 ... 0.01662204 1.         0.00434107]
 [0.03677182 0.00789863 0.00925323 ... 0.         0.00434107 1.        ]]


In [28]:
print(similarity.shape)

(189, 189)


In [29]:
# getting the movie name from the user
movie_name = input( 'Enter your favourite movie name :' )

Enter your favourite movie name :ironman


In [31]:
# creating a list with all the movie names given in the dataset
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [33]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches (movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man']


In [35]:
close_match = find_close_match[0]
print(close_match)

Iron Man


In [40]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print (index_of_the_movie)

68


In [41]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.010909509999674261)), (1, np.float64(0.03488966408602265)), (2, np.float64(0.004208914061970304)), (3, np.float64(0.004244736759183375)), (4, np.float64(0.010150180543347122)), (5, np.float64(0.003987948599758467)), (6, np.float64(0.07562067230948083)), (7, np.float64(0.13491008066309926)), (8, np.float64(0.0)), (9, np.float64(0.023692732554582922)), (10, np.float64(0.012463562707841793)), (11, np.float64(0.0035184879425672463)), (12, np.float64(0.0)), (13, np.float64(0.00394709274892248)), (14, np.float64(0.02893881761810885)), (15, np.float64(0.0)), (16, np.float64(0.16658333109390472)), (17, np.float64(0.0038268002773757265)), (18, np.float64(0.010161602552813696)), (19, np.float64(0.0035629704638011623)), (20, np.float64(0.04275238176979961)), (21, np.float64(0.0034830383041524805)), (22, np.float64(0.0)), (23, np.float64(0.0)), (24, np.float64(0.0)), (25, np.float64(0.0)), (26, np.float64(0.14396412896159935)), (27, np.float64(0.010096075446546964)), (28, np.floa

In [42]:
len(similarity_score)

189

In [43]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(68, np.float64(1.0)), (79, np.float64(0.20781648838665823)), (31, np.float64(0.1966039659674902)), (16, np.float64(0.16658333109390472)), (26, np.float64(0.14396412896159935)), (7, np.float64(0.13491008066309926)), (46, np.float64(0.10080688944405547)), (33, np.float64(0.09120045518028283)), (103, np.float64(0.0879292067752933)), (39, np.float64(0.08405313779888254)), (85, np.float64(0.08052826910442358)), (91, np.float64(0.07900852942154143)), (6, np.float64(0.07562067230948083)), (101, np.float64(0.07498646384795524)), (64, np.float64(0.06615704793359682)), (38, np.float64(0.06571197435460038)), (28, np.float64(0.056839279405948906)), (176, np.float64(0.055887403318964475)), (78, np.float64(0.04621452534107703)), (76, np.float64(0.045118914015666665)), (96, np.float64(0.04336206802446202)), (168, np.float64(0.04307697078199649)), (54, np.float64(0.042862220349064936)), (20, np.float64(0.04275238176979961)), (94, np.float64(0.041966560652827466)), (30, np.float64(0.04159638065515976

In [46]:
# print the name of similar movies based on the index
print('Movies suggested for you: \n')
i=1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<20):
    print(i, '.', title_from_index)
    i+=1

Movies suggested for you: 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . The Avengers
5 . Captain America: Civil War
6 . Avengers: Age of Ultron
7 . X-Men: Days of Future Past
8 . X-Men: The Last Stand
9 . Sherlock Holmes: A Game of Shadows
10 . TRON: Legacy
11 . Captain America: The Winter Soldier
12 . Independence Day: Resurgence
13 . Tangled
14 . X2
15 . X-Men: Apocalypse
16 . The Amazing Spider-Man 2
17 . Jurassic World
18 . Planet of the Apes
19 . The Jungle Book


Movie Recommendation Sytem

In [48]:
movie_name = input(' Enter your favourite movie name: ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches (movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values [0]

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you: \n')

i=1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<20):
    print(i, '.', title_from_index)
    i+=1

 Enter your favourite movie name: iron man
Movies suggested for you: 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . The Avengers
5 . Captain America: Civil War
6 . Avengers: Age of Ultron
7 . X-Men: Days of Future Past
8 . X-Men: The Last Stand
9 . Sherlock Holmes: A Game of Shadows
10 . TRON: Legacy
11 . Captain America: The Winter Soldier
12 . Independence Day: Resurgence
13 . Tangled
14 . X2
15 . X-Men: Apocalypse
16 . The Amazing Spider-Man 2
17 . Jurassic World
18 . Planet of the Apes
19 . The Jungle Book
